ACCEPT CIUDAD PROMPT '¿QUE CIUDAD?'
SELECT *
FROM CARRETERA
WHERE CODIGO IN (SELECT CODIGO
				FROM TRAMO
				WHERE CARRETERA.CODIGO=TRAMO.CODIGO
				AND CIU_ORI='&CIUDAD'
				OR CIU_DES='&CIUDAD');