ACCEPT FECHA PROMPT '¿QUE FECHA?'
SELECT * 
FROM PEDIDO
WHERE NOT EXISTS(SELECT *
		FROM LINEA
		WHERE PEDIDO.NUM_PEDIDO=LINEA.NUM_PEDIDO
		AND MATRICULA IN(SELECT DISTINCT REM_MATRICULA
					FROM CAM_REM
					WHERE EXISTS(SELECT DISTINCT MATRICULA
								FROM CAMION
								WHERE FECHA_ALTA<TO_DATE('&FECHA','DD/MM/YYYY/'))));
