ACCEPT CIUDAD PROMPT '¿QUE CIUDAD?'
SELECT DISTINCT CAM_MATRICULA
FROM CAM_REM
WHERE NOT EXISTS(SELECT *
			FROM REM_PAR
			WHERE REM_MATRICULA=MATRICULA
			AND EXISTS(SELECT *
							FROM PARQUE
							WHERE REM_PAR.NOM_PARQUE=PARQUE.NOM_PARQUE
							AND NOM_CIU='&CIUDAD'));
